on:
  workflow_dispatch:
  push:
    paths:
      - 'model/diagrams/SketchModel_id-42fbb7f0aed84dd39a512d34f4481a67.xml' 

jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy Archi report
        id: archi
        uses: WoozyMasta/archimate-ci-image@5.0.2-1.0.4
        with:
          archiHtmlReportEnabled: true
          archiJasperReportEnabled: true
          archiJasperReportFormats: PDF,DOCX
          archiCsvReportEnabled: true
          archiExportModelEnabled: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
